=== muleforge/Mule-IDE/src/test/plugins/org.mule.ide.config.common.tests/model/vehiclePark.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="urn:vehiclePark" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:vp="urn:vehiclePark">

    <complexType name="VehicleType">
    	<sequence>
    		<element ref="vp:Make"></element>
    		<element ref="vp:Model"></element>
    		<choice minOccurs="0" maxOccurs="unbounded">
    			<element ref="vp:Decal"></element>
    			<element ref="vp:Paint"></element>
    		</choice>
    	</sequence>
    </complexType>

    <element name="Make" type="string"></element>

    <element name="Model" type="string"></element>

    <element name="Paint" type="string"></element>

    <element name="Decal">
    	<complexType>
    		<attribute name="style" type="string"></attribute>
    		<attribute name="color" type="string"></attribute>
    	</complexType>
    </element>

    <element name="AbstractVehicle" type="vp:VehicleType" abstract="true"></element>

    <element name="Vehicle" type="vp:VehicleType" substitutionGroup="vp:AbstractVehicle"></element>

    <element name="Park">
    	<complexType>
   			<sequence minOccurs="1" maxOccurs="unbounded"><element ref="vp:AbstractVehicle"/></sequence>
    	</complexType>
    </element>
</schema>

=== muleforge/Mule-IDE/src/test/org.mule.ide.config.common.tests/model/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<vp:Park xmlns:vp="urn:vehiclePark" xmlns:cs="urn:cars" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:vehiclePark vehiclePark.xsd urn:cars cars.xsd ">
  <vp:Vehicle>
    <vp:Make>Form</vp:Make>
    <vp:Model>Fusion</vp:Model>
    <vp:Decal style="stripe" color="white"/>
    <vp:Paint>egg shell</vp:Paint>
    <vp:Decal color="blue" style="stripe"/>
    <vp:Decal style="tribal"/>
  </vp:Vehicle>
  
  <cs:Car>
  	<vp:Make>fisk</vp:Make>
  	<vp:Model>fisk</vp:Model>
  </cs:Car>
  
</vp:Park>
